# Generated by Django 6.0.1 on 2026-01-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailotp_purpose'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='emailotp',
            constraint=models.UniqueConstraint(condition=models.Q(('is_verified', False)), fields=('user', 'purpose', 'is_verified'), name='one_active_otp_per_user_purpose'),
        ),
    ]
