# Generated by Django 6.0.1 on 2026-01-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_emailotp_options_alter_emailotp_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
