# Generated by Django 6.0.1 on 2026-01-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_university_description_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Numeric duration (e.g. 2, 3, 4, 6, 8)', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_unit',
            field=models.CharField(blank=True, choices=[('year', 'Year'), ('semester', 'Semester')], help_text='Year or Semester', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='curriculum_type',
            field=models.CharField(choices=[('semester', 'Semester'), ('year', 'Year')], help_text='Academic structure followed by the course', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
