# Generated by Django 6.0.1 on 2026-01-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_remove_course_created_at_remove_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(help_text='Numeric duration (e.g. 2, 3, 4, 6, 8)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_unit',
            field=models.CharField(choices=[('year', 'Year'), ('semester', 'Semester')], help_text='Year or Semester', max_length=10),
        ),
    ]
