# Generated by Django 6.0.1 on 2026-01-28 09:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
