# Generated by Django 6.0.1 on 2026-02-12 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_alter_book_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('semester', 'Semester'), ('year', 'Year')], max_length=10)),
                ('number', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='education.course')),
            ],
            options={
                'unique_together': {('course', 'number', 'period_type')},
            },
        ),
    ]
