# Generated by Django 6.0.1 on 2026-02-13 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_academicperiod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicperiod',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='education.academicperiod'),
        ),
        migrations.AlterField(
            model_name='book',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='education.course'),
        ),
    ]
