# Generated by Django 6.0.1 on 2026-02-13 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_alter_academicperiod_options_academicperiod_order_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('period', 'name')},
        ),
        migrations.AlterField(
            model_name='book',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='education.academicperiod'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='course',
        ),
    ]
